# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20161206_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fun_facts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
