# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20161206_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='dept',
            field=models.ForeignKey(blank=True, db_column='dept_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Department'),
        ),
    ]
